apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: test-service
  namespace: test
spec:
  host: service.<Ingress_Domain> 
  port:
    targetPort: 8080 
  to:
    kind: Service
    name: hello-openshift
